apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: k8s-java-config-reload
  name: k8s-java-config-reload
spec:
  containers:
    - image: k8s-java-config-reload
      name: k8s-java-config-reload
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
